name: totv_plus
description: ToTV+ - Live TV & VOD Streaming Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Dependency Injection (تم التعديل هنا ليتوافقا معاً ومع Dart 3.5)
  get_it: ^8.0.0
  injectable: ^2.3.2
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^7.0.0
  
  # Video Player
  video_player: ^2.8.1
  better_player:
    git:
      url: https://github.com/jhomlala/betterplayer.git
      ref: master
  chewie: ^1.7.4
  wakelock_plus: ^1.1.4
  
  # Firebase
  firebase_core: ^4.4.0
  firebase_remote_config: ^6.1.4
  firebase_analytics: ^12.1.2
  firebase_crashlytics: ^5.0.7
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0        # متوافق مع Dart 3.5
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.20.2
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.2
  path_provider: ^2.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0       # متوافق مع Dart 3.5
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/m3u/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
